#pragma once
#define IMGUI_DEFINE_MATH_OPERATORS
#include <thirdparty/memory/memory.h>
#include <d3d11.h>
#include <D3DX11tex.h>
#include <tchar.h>
#include <src/cache/index.h>
#include <windows.h>
#include <iostream>
#include <string>
#include <vector>
#include <thread>
#include <numbers>
#include <algorithm>
#include <optional>
#include <mutex>
#include <unordered_map>
#include <tlhelp32.h>
#include <dwmapi.h>